### ISSUE TITLE
getLocation does need 15 seconds to show userLocaton

### ISSUE THREAD

**Issue by royvano** [malcommac/SwiftLocation#125]
When I use Location.getLocation, it needs like 15 seconds to load my current location.
I've updated the pod but this doesn't affect it.

I checked if any of my functions would be doing this, but when I print "hello" before the func and "hello2" in the function where the location is displayed. The first "hello" is printed immediately, and the "hello2" is only printed after those 15 seconds.

When I used SwiftLocation for the first time (Month ago) I didn't have such problems. Does anybody got the same problem?

**Comment by malcommac** [comment]
can you paste here your func to get the current location? The time required to get first valid result (where valid is the accuracy you have requested) depends by the hardware + accuracy requested.

**Comment by ghost** [comment]
Same here. This is my simple code:
`let request = Location.getLocation(accuracy: .house, frequency: .oneShot, timeout: 30.0, success: { (_, location) -> (Void) in
            success(location)
        }) { (request, location, error) -> (Void) in
            err(error)
        }`

It works seamlessly when the device is connected with Xcode or on simulator, but when I use it just on my phone (iPhone5), the duration of receiving location varies. It takes between 1 second and 30-60 seconds to get the value through callback.

It seems there is a bug because lastLocation has got a value immediately.

Does someone have any idea what may affect the efficiency of getting location?

**Comment by iThinker** [comment]
@localsDeveloper any luck? I am investigating issue with project that uses this pod. It looks like it should work fine. But for whatever reason it gets out location worse than GoogleMaps. I've tried setting all best parameters but no luck.

**Comment by golovnya** [comment]
@localsDeveloper  Use accuracy `.any` to get user's current location.

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.
