### ISSUE TITLE
how to check the current auth status from swiftlocation ??

### ISSUE THREAD

**Issue by rohitgarg4989** [malcommac/SwiftLocation#140]
how to check the current auth status from swiftlocation ??

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.

Current status can be obtained by calling `CLLocationManager.authorizationStatus`
