### ISSUE TITLE
Background Request

### ISSUE THREAD

**Issue by imran87** [malcommac/SwiftLocation#145]
How can I create background request.

here below is my code but called when app is in background mode.

    var locationManager: CLLocationManager = CLLocationManager()
    locationManager.allowsBackgroundLocationUpdates = true
    locationManager.requestAlwaysAuthorization()

        if CLLocationManager.authorizationStatus() == .notDetermined{
            locationManager.requestAlwaysAuthorization()
        }
        Location.locationManager(locationManager, didChangeAuthorization: .authorizedAlways)
1)  Location.locationManager(locationManager, didChangeAuthorization: .authorizedAlways)
        
        Location.getLocation(accuracy: .house, frequency: .continuous, success: { (request, location) -> (Void) in
            
            print(location)
            
        }) { (request, lastValidLocation, error) -> (Void) in
            request.cancel()
        }

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.

A background section is available on README file and describe how significant location monitoring works.
