### ISSUE TITLE
appAuthorization in monitorVisit: why not .both, instead .always?  

### ISSUE THREAD

**Issue by alexandremorgado** [malcommac/SwiftLocation#149]
In VisitsRequest init, SwiftLocation does this guard: 

```
guard CLLocationManager.appAuthorization == .always else {
	throw LocationError.other("NSLocationAlwaysUsageDescription in Info.plist is required to use Visits feature")
}
```

But this guard shouldn't check also for **.both** status, once .both means always authorization is present?

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.

Visiting is not yet supported in 3.x branch. I'll restore it for 3.1.
If you have suggestions feel free to open a new issue
