### ISSUE TITLE
How to stop location continuos

### ISSUE THREAD

**Issue by horaciosolorio** [malcommac/SwiftLocation#150]
Can you help me please i need to stop location updates in viewDidDisappear, i run your example in view will appear but i what to stop when enter to viewDidDisappear.

Please help.

**Comment by nelsongc** [comment]
var locInstantce = Location.getLocation(...)
..
...
locInstantce.cancel()

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.

To stop a request use `stopRequest()` function of the `Locator` object
