### ISSUE TITLE
Location Monitor Pool? 

### ISSUE THREAD

**Issue by SalAldana** [malcommac/SwiftLocation#161]
Is there a way to get the pool of locations that are being monitored when using Location.monitor? In our previous setup using just CoreLocation there are times where we needed to cycle through all the monitored regions in LocationManager.monitoredRegions so we can remove any duplicates or regions that are no longer within a certain radius of the users. Can't seem to find anything in the documentation that shows whether you can/can't access the Location pool. This is the one thing missing that would SwiftLocation a complete replacement for our current structure. Thanks.

**Comment by malcommac** [comment]
Thank you for your contribution.
A new rewritten version is available both on master and CocoaPods (marked as 3.0.0-beta). It requires iOS9 and Swift 4.
If you encounter any other problem feel free to open an issue; I'll close because with the new version its now invalid.

Current version does not support region monitoring yet. It's planned for incoming 3.1 release. If you have questions or suggestions feel free to reopen a new issue.
Thanks

**Comment by SalAldana** [comment]
Thanks @malcommac for the response and updated library. Not to rush or sound ungrateful, but do you know when you may have 3.1 with the replacement for the 'Location.monitor(region:' in place? I had just got the whole background updates and location monitoring finished on Friday and now the monitor method is gone :( . 

Really great library, I've been using this and SwiftDate on a couple projects now and both have made life so much easier.

**Comment by malcommac** [comment]
Thank you very much, I'll try to work on it this week but I can't make any promise about that because I'm pretty busy with another project.
You can follow it here: https://github.com/malcommac/SwiftLocation/issues/162

**Comment by SalAldana** [comment]
No problem, I'll roll back for now just because the monitor part is important for the testing we are doing but will bookmark this to update when ready. Thanks again for everything.
