### ISSUE TITLE
Why I can not see the Locator variable?

### ISSUE THREAD

**Issue by Eric0625** [malcommac/SwiftLocation#170]
It's SwiftLocation (2.0.7) and I can't find the locator.swift in the pod files

**Comment by Eric0625** [comment]
![default](https://user-images.githubusercontent.com/18132007/32984783-06caa7e8-cce8-11e7-8117-627355071b19.PNG)

**Comment by SalAldana** [comment]
Locator is part of the 3.0 re-write. If you are using the older version then download the source code here and use the README in the source code to get the correct syntax/instructions. 

https://github.com/malcommac/SwiftLocation/releases/tag/2.0.7

**Comment by Eric0625** [comment]
Thx, I'm trying beta version now

**Comment by jmeyers91** [comment]
Does version 2.0.7 work if installed through CocoaPods? I have `pod 'SwiftLocation', '~> 2.0.7'` in my podfile and it appears to install successfully when I run `pod install`, but I'm still receiving `Use of unresolved identifier 'locator'` (with `import SwiftLocation` at the top of the file) after cleaning.

**Edit**: Never mind. I thought 2.0.7 was the new version because `pod 'SwiftLocation'` installed version 1.x.x. Changing the version in my podfile to 3.0.1-beta fixed the issue.
