### ISSUE TITLE
Feature: requestAuthorizationIfNeeded should take you to settings if system authorization prompt has already been presented

### ISSUE THREAD

**Issue by nderkach** [malcommac/SwiftLocation#172]
Here is how this could work when you call requestAuthorizationIfNeeded:

- If the system location authorization prompt has never been presented -> present the system prompt
- otherwise, open the URL at `UIApplicationOpenSettingsURLString`

This would save time implementing the boilerplate code for checking if `CLLocationManager.authorizationStatus() == .notDetermined`

**Comment by malcommac** [comment]
Hi,
Actually SwiftLocation ask the right level of authorization by reading the Info.plist keys.
See the `requestAuthorizationIfNeeded` function at https://github.com/malcommac/SwiftLocation/blob/f0cfe69cce74df8279e2606e6017b260f6fc77f2/Sources/Locator.swift#L513.
Did it not work for you?

The second part of your question: I cannot assume developer wanna go the Settings panel automatically (especially because `UIApplicationOpenSettingsURLString` bring you to the root of the Settings, not application's location panel).

I've also tried to use the `App-Prefs:root=Privacy&path=LOCATION` url but it does not work anymore on iOS 11 (and btw is a private API).

**Comment by nderkach** [comment]
No, the first part works just fine, my suggestion for was the case when the user has previously rejected the location authorization prompt.

Why wouldn't you want to go to the settings panel automatically? Assuming you have a button which allows the user to enable location updates and implemented `requestAuthorizationIfNeeded` action for it. How would you handle the case when a user previously denied location authorization?
