### ISSUE TITLE
Support for deferredLocationUpdates

### ISSUE THREAD

**Issue by imran87** [malcommac/SwiftLocation#174]
Not Working which really very very important thing in code.

**Comment by malcommac** [comment]
Is it working for you?

I've planned to implement it but it does not work since iOS 9; it simply return `false` everytime (`CLLocationManager.deferredLocationUpdatesAvailable()`).
See for example this:
http://openradar.appspot.com/radar?id=4927958787555328

If you are using it successfully I'm very interested in looking some example code and I'll be happy to integrate it in SwiftLocation.
