### ISSUE TITLE
Background thread

### ISSUE THREAD

**Issue by radvansky-tomas** [malcommac/SwiftLocation#175]
Can somebody explain why I cannot run: Locator.currentPosition(accuracy: .house, timeout: nil, onSuccess: { (loc) -> (Void) in background thread ? 

Or what is my option if I want to perform single one shot in background ? 

Or if there is no such feature, how I can run: Locator.subscribePosition
With custom frequency and distance of last location (ie. custom significance)

**Comment by malcommac** [comment]
There is a reason:

`
A location manager was created on a dispatch queue executing on a thread other than the main thread.  It is the developer's responsibility to ensure that there is a run loop running on the thread on which the location manager object is allocated.  In particular, creating location managers in arbitrary dispatch queues (not attached to the main queue) is not supported and will result in callbacks not being received.
`

You don't need to perform a location request in background because CLLocationManager already works in background.
