### ISSUE TITLE
Fixes for Place parser from Apple services. Unified shared properties terminology between services.

### ISSUE THREAD

**Issue by Nerkyator** [malcommac/SwiftLocation#192]
`houseNumber` is mapped with wrong infos: right now its value is mapped to `subAdministrativeArea` that actually is not a house number but an area\district

**Comment by malcommac** [comment]
Can you made a PR or tell me the detail of the mapping?

**Comment by Nerkyator** [comment]
Sure!
Here are mapping details:
Lat: 45.383456971377598
Lon: 10.4940416764875

I attach a debug object screenshot too just to be clear
<img width="356" alt="schermata 2018-03-19 alle 11 34 39" src="https://user-images.githubusercontent.com/4661466/37590829-c130cb50-2b69-11e8-9f3d-d9ac8e4aaedb.png">

**Comment by malcommac** [comment]
Ok reading [documentation](https://developer.apple.com/library/mac/Documentation/CoreLocation/Reference/CLPlacemark_class/index.html#//apple_ref/occ/instp/CLPlacemark/thoroughfare) the best result is ` subThoroughfare`:

> Subthroughfares provide information such as the street number for the location. For example, if the placemark location is Apple’s headquarters (1 Infinite Loop), the value for this property would be the string “1”.

As for name, that's simply the name that the system has for the placemark. For some places, it will just be the address; in fact for your location it return `nil`.
Fixed.

## Further Changes

With the intent to unify all these strings and fix errors I've deprecated (since 3.2.1) the following properties:

* `state` (use `administrativeArea`)
* `county` and `cityDistrict` (use `subAdministrativeArea`)
* `neighborhood` (use `locality`)
* `postcode` (use `postalCode`)
* `road` (use `thoroughfare`)
* `houseNumber` (use `subThoroughfare`)

Now `rawDictionary` contains a valid dictionary for data retrived using Apple's geocoding service.
