### ISSUE TITLE
Stop a current position request (LocationRequest)

### ISSUE THREAD

**Issue by himanthmaddi** [malcommac/SwiftLocation#214]
I have subscribed for significant location updates even in background. Now if I want to stop updating locations at particular scenarios like after user has signed off, how can I do that by using **SwiftLocation**

**Comment by basmaamahmoud** [comment]
you use locationManager.startUpdatingLocation() to start updating location and use locationManager.stopUpdatingLocation() to stop updating location

**THIS IS NOT THE RIGHT WAY. CHECKOUT THE POST BELOW**

**Comment by malcommac** [comment]
When you register a new request using `currentPosition()` call you receive the request (an instance of `LocationRequest`). You can keep a reference to it and use `stop()` function to remove it from the queue.

locationManager's `stopUpdatingLocation()` and `startUpdatingLocation()` should be not used because SwiftLocation manage itself from the inside by stopping/resuming the system location manager based upon the active request.
This is true both for location and heading.

See the `Managing Requests or Subscriptions Lifecycle` section in readme.
