### ISSUE TITLE
Fixed error while subscribing heading updates (authorization + minimum accuracy filter)

### ISSUE THREAD

**Issue by pingusNikalex** [malcommac/SwiftLocation#232]
I will try to use 

```swift
Locator.subscribeHeadingUpdates(accuracy: 2, onUpdate: { (newHeading) -> (Void) in
  print("New heading \(newHeading)")
}) { (error) -> (Void) in
  print("Failed with error: \(error)")
}
```
But always has error: `Failed with error: invalid`

**Comment by malcommac** [comment]
Thank you for your report.
I've fixed two different issues:

- The first one happens the first time you attempt to launch the subscription and prevent the correct request for authorization to the end user.
- The second one filter all results from heading service due to a wrong statement.

It will be part of the 3.3.0 release.
