### ISSUE TITLE
Getting continous updates with fixed min time intervals/min distance

### ISSUE THREAD

**Issue by yogendragirase55** [malcommac/SwiftLocation#248]
Hi Team 

I need to get continue location for every 5 min and change 100 meter around last location.

So how can I get continue location every 5 min. please help me which method I can use and set timer 5 min.

**Comment by malcommac** [comment]
Hi,
Since 4.1.0 I've added the `dataFrequency` property inside the `LocationRequest` object. It's an enum:

```
// Data frequency to receive events
 enum DataFrequency {
  case asAvailable
  case fixed(minInterval: TimeInterval?, minDistance: CLLocationDistance?)
}
```

By default value for a new `LocationRequest` is `asAvailable` which means "no filters on frequency data`. You can also set it to `fixed` by specifying one or both the constraints (by minimum time and minimum distance, expressed in meters).

This is an example of the code.

```swift
let request = LocationManager.shared.locateFromGPS(.continous, accuracy: .city) { data in
            switch data {
            case .failure(let error):
                print("Location error: \(error)")
            case .success(let location):
                print("New Location: \(location)")
            }
        }
request.dataFrequency = .fixed(minInterval: 40, minDistance: 100) // minimum 40 seconds & 100 meters since the last update. 
```

Thanks for your suggestion.
