### ISSUE TITLE
[4.0.1] lastAbsoluteLocation in request closure

### ISSUE THREAD

**Issue by alexanderkorus** [malcommac/SwiftLocation#256]
I'm implementing now version 4.0.1 and replacing the old one. 
Now there is a field in the locationRequest named "lastAbsoluteLocation". I want to access this last location, when my locationRequest failed (for example because of a timeout). The problem is, I can't access it in the request closure, only over the locationRequest itself. 
Is it possible to add this lastLocation to the ErrorReason 

```swift
LocationManager.shared.locateFromGPS(.oneShot,
       accuracy: .house,
       timeout: Timeout.Mode.delayed(30.0)
) { (result: LocationRequest.Data) in
             switch result  {
                  case .success(let location):
                       print("GET Location Success: \(location)")
                       // doing something with location
                   case .failure(let error):
                       print("GET Location Error: \(error)")
                       // I want to accèss lastAbsoluteLocation here
              }
 }
```

**Comment by malcommac** [comment]
Due to the the structure of the `Result` type in swift we cannot pass the instance of the request as error; we could pass it along with one of the available error enums but this mean we need to have different sets of the errors for each type of request which is not best solution.

Since 4.0.2 `LocationRequest` produces a new error when timeout is reached without a valid location received; this is called `requiredLocationNotFound` and it includes the timeout interval and the last absolute location found (request's `lastAbsoluteLocation` property value).

So your code will be something like this:

```swift
LocationManager.shared.locateFromGPS(.oneShot,
       accuracy: .house,
       timeout: Timeout.Mode.delayed(30.0)
) { (result: LocationRequest.Data) in
             switch result  {
                  case .success(let location):
                       print("GET Location Success: \(location)")
                       // doing something with location
                   case .failure(let error):
                      switch error: {
                         case . requiredLocationNotFound(let interval, let lastLocation):
                            // lastLocation is the last absolute location received from GPS module
                         default:
                            break
                       }
                       print("GET Location Error: \(error)")
                       // I want to accèss lastAbsoluteLocation here
              }
 }
```
Thanks for your report.
