### ISSUE TITLE
locateFromGPS just stopped working. Please help

### ISSUE THREAD

**Issue by saparfriday** [malcommac/SwiftLocation#293]
Hello developers. The method .locateFromGPS today just stopped working, before that, 6 months worked without problems.

Example code:
```
LocationManager.shared.locateFromGPS(.oneShot, accuracy: .block) { (result) in
            switch result {
            case .failure(let error):
                print(error.localizedDescription)
            case .success(let location):
                print(location.coordinate)
            }
}
```

Translate error:
Failed to complete the operation. (SwiftLocation.LocationManager.ErrorReason, error 2)

**Comment by eminisrafil** [comment]
Any luck?

**Comment by vaibhav-jhaveri-ds** [comment]
@SapaTech @eminisrafil @malcommac Any updates on this?

**Comment by Strobocop** [comment]
@SapaTech what version of iOS? I am experiencing a similar issue that I think may be due to iOS 14's new approximate location setting. 

Edit: Just noticed there is a [PR](https://github.com/malcommac/SwiftLocation/pull/295) up related to this. Not sure if it solves my issue yet or not but will report back.

**Comment by lex-shvets** [comment]
Any update on this [PR](https://github.com/malcommac/SwiftLocation/pull/295)? Would be very nice to merge it!

**Comment by AravindBG** [comment]
Location is not getting from **locateFromGPS** method in iOS 14. 
SwiftLocation version 4.2.0 
Any update on this?
