### ISSUE TITLE
Stop GPS Continous values

### ISSUE THREAD

**Issue by Lallering** [malcommac/SwiftLocation#308]
I am having a problem and it is that once I start a continuous gps subscription I cannot stop it since the subscription UUID that returns me is different from the one that started, i save the request UUID in the gpsRequest variable and use it later to cancel the created request
![image](https://user-images.githubusercontent.com/33471019/99986114-6a6e4580-2d74-11eb-8e54-b70654d326e6.png)
This is what i get when i start it
![image](https://user-images.githubusercontent.com/33471019/99986328-ac978700-2d74-11eb-93e9-d2a4012cdc74.png)
then I call this function to stop the request with the UUID that was provided to me
![image](https://user-images.githubusercontent.com/33471019/99986393-bf11c080-2d74-11eb-9b3c-07278eebf480.png)
and then this answer appears in the console:
_Failed to remove request: '4F633ED4-4AD1-435E-BF69-4E9948AE9D07'_.
Different from UUID: _031D710D-C3A9-4D18-99EF-B92885D225A5_ that appeared at startup, i don't know if it's a bug or if I'm doing something wrong.

**Comment by malcommac** [comment]
Hi,
There is something wrong; are you sure your `gpsRequest` is a `GPSLocationRequest` object?
Because this logging message happens when the library cannot cast passed object to a known object; take a [look here](https://github.com/malcommac/SwiftLocation/blob/9f9a81b084afac692e26b213bca5715271bf6f25/Sources/SwiftLocation/SwiftLocation.swift#L347):

```swift
 public func cancel(request: Any) {
        switch request {
        case let location as GPSLocationRequest:
            gpsRequests.remove(location)
        ... 
        default:
            LocationManager.Logger.log("Failed to remove request: '\(request)'")
        }
    }
```

Can you get the type of the object?

**Comment by malcommac** [comment]
i'll close it due to inactivity
