### ISSUE TITLE
Requesting "Always" Authorization from the library

### ISSUE THREAD

**Issue by yaszakharov** [malcommac/SwiftLocation#352]
Hello!
I can't request Always Authorization in iOS 14. If I call manually request modal window with Auth Request not showing, but while I'm using default CoreLocation library, dialog with Auth Request showing.

```swift
SwiftLocation.requestAuthorization(.always) { newStatus in
            print("New status \(newStatus.description)")
}
```

Thank you!

**Comment by malcommac** [comment]
Hi, have you correctly configured your Info.plist?

You sshould set the appropriate keys in your Info.plist (`NSLocationAlwaysAndWhenInUseUsageDescription` or `NSLocationWhenInUseUsageDescription` and `NSLocationTemporaryUsageDescriptionDictionary` if you are using reduced location in iOS 14+).

If you still experiencing the problem attach here a simple project to reproduce it because looking at the playground project it works properly.
Thanks.

**Comment by yaszakharov** [comment]
In playground project on Simulator iOS 14.5 Request Authorization not working, please check that. I'm set in settings "While Using In the App" trying Request Always Auth from Playground App, I'm view "Current Status is whenInUse" and Always Auth not requested.
