### ISSUE TITLE
desiredAccuracy vs minimum accuracy

### ISSUE THREAD

**Issue by bcbeta** [malcommac/SwiftLocation#360]
Request.accuracy sets the minimum accuracy so that any location with worse accuracy is discarded. How does one set the desiredAccuracy of the LocationManager for example to kCLLocationAccuracyBestForNavigation?

**Comment by b00tsy** [comment]
I also think `GPSLocationOptions` needs a second parameter distinguishing between `desiredAccuracy` of `CLLocationManager` and the filter that is being applied on the data in `GPSLocationRequest.validateData`.

The intention of `desiredAccuracy` in `CLLocationManager` is to set the hardware into the desired mode, which results in eg. iOS delivering data of the gps sensor corrected by additional sensor data or use location data connected to wifi networks or maybe even based on ip addresses.

However, that is just a "hey iOS I want data of this accuracy call" and not a guarantee that you get what you asked for. Eg. when asking for `kCLLocationAccuracyBestForNavigation` you still could get gps data with an accuracy of ±10 m, because either the hardware is not fired up, yet, or maybe the hardware is just not able to deliver data of such accuracy in the current circumstances. Still getting such less accurate data would be better than getting no data at all, because currently `GPSLocationRequest.validateData` filters ie. discards all data that does not match the specified accuracy. 

Currently to bypass such problems one needs to lower the accuracy which again sets the hardware into a not desired state of less accuracy.

A better approach would be to have a customizable option eg. `minAccuracy` which would be the filter applied in `GPSLocationRequest.validateData` to the data received and a `desiredAccuracy` which would set the desired accuracy of the hardware.
