### ISSUE TITLE
Accuracy House + Room + Navigation don't work

### ISSUE THREAD

**Issue by luskin** [malcommac/SwiftLocation#48]
if you choose location accuracy house or room you get no responses...

**Comment by ghost** [comment]
This is happening for me too, except house is working for me. House is the most detailed I can get.

**Comment by dkrusenstrahle** [comment]
Same error for me. Hard to use it without these accuracies.

**Comment by dkrusenstrahle** [comment]
Any solution to this? Or perhaps a suggestion for other pod?

**Comment by luskin** [comment]
No solution, I had to end up not using this package.

**Comment by malcommac** [comment]
Take a look to 1.0.0 and tell me if it works

**Comment by MetalheadSanya** [comment]
Use 1.0.0, get this issue. With `.Block` all work correct.

**Comment by malcommac** [comment]
I've made some further investigations and I've found a logic error (fixed in https://github.com/malcommac/SwiftLocation/commit/805899038ceb084bbe104acef1a2b4fbca10c622 and available in 1.0.1 I'll publish in less than an hour).

In fact both `.Room` and `.Navigation` uses `kCLLocationAccuracyBest` and `kCLLocationAccuracyBestForNavigation` which does not mean a valid fixed value (a `CLLocationAccuracy` which identify the meters of uncertainly) but the best value which the phone can achieve (by consuming higher energy).
So the value we can accept for both the value is `< kCLLocationAccuracyNearestTenMeters`. If you use `.OneShot` you will receive the first value below `kCLLocationAccuracyNearestTenMeters` GPS module can receive. Theoretically with `.Continuous` location scan you may receive  better values (this always depends by several external factors).
I'll publish this update quickly. Thank you for your report.
