### ISSUE TITLE
get user location as first thing

### ISSUE THREAD

**Issue by AsimNet** [malcommac/SwiftLocation#59]
Hello

i'm trying to get user's location in viewDidLoad using this closure : 

``` swift
   var userLocation = CLLocation()
        Location.getLocation(withAccuracy:  .IPScan, onSuccess: { (location) in
            // approximate location is here
             userLocation = location

        }) { (lastValidLocation, error) in
            // something wrong has occurred; error will tell you what
        }
```

but I found out that the `userLocation` is (0.00,0.00) 

how to solve this problem without implementing CLLocation methods ?

thanks.

**Comment by malcommac** [comment]
Question is not related to SwiftLocation, it's a general programming question.
`getLocation()` as the other methods works asynchronously.
Moreover seems your `userLocation`variable is allocated then discarded because no one outside the scope of the function where this snipped is executed keep it alive.
If you want to keep it alive and update when the location is found you need to declare it somewhere else.
Just for example, suppose you have your code in your UIViewController:

``` swift
class ViewController: UIViewController {
       var lastLocation: CLLocation? // it will be nil until the location were found

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.

        Location.getLocation(withAccuracy: .IPScan, onSuccess: { (loc) in
            lastLocation = loc
                       // do something else...
             }) { (last, err) in
              // something went wrong...
        }
...
...
```

Obviously this depending what you are trying to accomplish, this is just an example.
