### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by kwstasna** [malcommac/SwiftLocation#67]
Hello.
Nice library !
Does this work without the user to "Allow" taking his location?

**Comment by mohpor** [comment]
@kwstasna 
This library can get you user's location without user's permission with some draw backs:
- It needs a network connection (Not so much of a problem)
- The result is not at all reliable (Especially in case of cellular network which is the main audience here).
- If user is using VPN or a proxy, the result is completely invalid.

Generally speaking, you should use this method for acquiring user's country and city, more than that is highly unreliable. (Even country and city are invalid if user uses VPN for example.)

**Comment by kwstasna** [comment]
I'm actually using the default ios way to get the latitude and longitude of the user to send some requests.
That's why i'm asking. Is that possible to make it with high accuracy ?

**Comment by mohpor** [comment]
You see, it uses an API which looks up in a registered IP associated with a location data base. In most cases it might be your ISP's location and in case of your cellular network, god knows where. So that's the accuracy. It's always a good idea to use LocationService for the more accurate results, you can fallback to IPScan in case you want to fill out some part of a signup form at the beginning and don't want to bother user with an extra permission just yet.

**Comment by kwstasna** [comment]
Oh ok I understand now!
Thanks a lot!
